apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radicale.fullname" . }}
  labels:
    {{- include "radicale.labels" . | nindent 4 }}
stringData:
  users: |  
{{- if .Values.config.users }}
{{- range $user, $password := .Values.config.users }}
    {{ $user }}:{{ $password }}
{{- end }}
{{- end }}