apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radicale.fullname" . }}
  labels:
    {{- include "radicale.labels" . | nindent 4 }}
data:
  users: |
{{- if .Values.config.users }}
{{- range $user, $password := .Values.config.users }}
    {{ $user }}: {{ $password | b64enc }}
{{- end }}
{{- end }}